apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-papertrail
  namespace: kube-system
  labels:
    k8s-app: fluentd-papertrail
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-papertrail
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: fluentd-papertrail
        version: v1
        component: logger
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentd-logging
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: quay.io/solarwinds/fluentd-kubernetes:v1.2-debian-papertrail-0.2.7-bugfix
        imagePullPolicy: Always
        env:
          - name: FLUENT_PAPERTRAIL_HOST
            valueFrom:
              secretKeyRef:
                name: papertrail
                key: papertrail_host
          - name: FLUENT_PAPERTRAIL_PORT
            valueFrom:
              secretKeyRef:
                name: papertrail
                key: papertrail_port
          - name: FLUENT_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: papertrail
                key: fluentd_hostname
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 400Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: config
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluentd-papertrail-config
          items:
          - key: fluent.conf
            path: fluent.conf
          - key: kubernetes.conf
            path: kubernetes.conf


